name: Format and Commit Python Code

on:
  push:
    branches:
      - main

jobs:
  format_and_commit:
    name: Format and Commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort

      - name: Format with black and isort
        run: |
          black .
          isort .

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Auto-format code using black and isort"
          git push https://github.com/Shivesh777/coding.git HEAD:${{ github.ref }} --follow-tags

env:
  PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
